### ISSUE TITLE
Bug: Add Tripler button not working on tripler selection

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#110]
1. Login as an ambassador on https://stage2.app.blockpower.vote/blockpower
2. On `/triplers`  Click "Find new Vote Triplers" button
3. `/triplers/add` loads. Search for the first name Keith
4. Select checkbox next to Keith Bosco in list. Blue action header appears.
5. Click "Add 1 Tripler(s) to my list". Nothing happens. No network requests are made and no errors are seen in browser console 

Expected: Clicking "Add 1 Tripler(s) to my list" would load `/triplers` and show the selected tripler in the "Your possible Vote Triplers" list

**Comment by cooperka** [comment]
This is fixed in https://github.com/colab-coop/hello-voter/pull/109/commits/90121da1d39ec2751a225037d47096d72fa97f38. It broke from the most recent PR https://github.com/colab-coop/hello-voter/pull/108#issuecomment-696303074. Thanks for finding it so quick!
