### ISSUE TITLE
Select PayPal as payment method

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#118]
As an ambassador, I want to select PayPal as my preferred payment method.

- On /payments/add page, add a new button to left of "Use existing account" 
- Button title: `Use PayPal`
- Button subtitle: `Get set up quickly to receive payments with PayPal.`
- Include PayPal "PP" logo on button

- Clicking this new PayPal button should load a new page /payments/paypal . The page can follow the overall styles of /payments/chime but without an image at the top. 
- The page should have a PayPal logo at the top with full wordmark ([like this](https://seeklogo.net/wp-content/uploads/2015/11/paypal-logo-preview.png, header text `Confirm details for PayPal` and a prompt below `If you already have a PayPal account, please confirm the email address you use for your PayPal account below. If you don't have a PayPal account, you can still receive payments and set up an account when you are ready to claim your payments. Please enter the email address where you would like to receive PayPal payments below.` 
- Below the prompt, there should be a form with 1 required field for `Email address`. The field should be prepopulated with the ambassador's email address from signup, and a `Confirm` button
- Email submitted in this field should be updated as ambassador's email address in their profile
- The ambassador can edit the form or just click `Confirm` button. Once `Confirm` button is clicked, set `account?paypal=true`

**Comment by ajones620** [comment]
what happens if the user enters a different email address?

**Comment by cooperka** [comment]
Update: I made good progress on this so far, will try to submit a PR tonight after I finish the input form.

**Comment by shrutimehta13** [comment]
<img width="1059" alt="Screenshot 2020-10-10 at 5 28 20 PM" src="https://user-images.githubusercontent.com/34771314/95654648-03c3fe00-0b1f-11eb-9b81-93acb4c2b451.png">
