### ISSUE TITLE
Defect - Tripler List Not Sorted By Geographic Distance

### ISSUE THREAD

**Issue by ajones620** [colab-coop/hello-voter#123]
# Summary
Tripler search results are not sorted by closest geographic proximity, which likely means worse search results and fewer Tripler sign-ups.

## Current Behavior
When searching for triplers, if there are multiple search matches with the same name, the results are not sorted geographically.

For example, if I live in FL and search for "Jones" as a last name and if there are results from people in FL and AZ, I see the AZ people ahead of the FL people.

I also see results from people further away than 10km from my location even though there is text on the screen that says "Possible Vote-Triplers within 10km" at the top of the search results. (separate ticket for this issue: https://github.com/colab-coop/hello-voter/issues/113)

## Expected Behavior 
* When there are multiple results from a search term, I see the results sorted by closest geographic distance to me.

*Reference Screenshot (note that the test account ambassador location is NC)*
<img width="1107" alt="Screen Shot 2020-09-27 at 7 14 28 PM" src="https://user-images.githubusercontent.com/8608070/94383832-f9087280-00f5-11eb-88e3-43a2cd59ae3a.png">

**Comment by shauminn-colab** [comment]
Closing because I'm a dodo and it does actually appear to be sorting by geo-distance on serach results after all
