### ISSUE TITLE
Update copy and remove button on /payments/add

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#135]
- Update title copy on "Use existing account" button to `Link bank account`
- Update subtitle copy on same button to `Connect your bank account quickly and securely to receive payments.`
- Remove `Go Back to Payments` button

**Comment by shrutimehta13** [comment]
<img width="1215" alt="Screenshot 2020-10-10 at 5 20 58 PM" src="https://user-images.githubusercontent.com/34771314/95654420-759b4800-0b1d-11eb-81ca-0776f91f338e.png">
