### ISSUE TITLE
DEFECT - On Android Chrome Browser, Tripler Search Results Are Scrolled to Bottom of List

### ISSUE THREAD

**Issue by ajones620** [colab-coop/hello-voter#138]
# Summary/Current Behavior
When I search for Triplers on the **/triplers/add** page using Chrome mobile browser on Android, I see the results scrolled to the bottom of the results list. See screenshot 1.

I was using Chrome 85.0.4183.127 on OS Android 11; Pixel 2 Build/RP1A.200720.009. See screenshot 2.

This is an issue because results are sorted by geographic distance to the Ambassador. Some Ambassadors have reported seeing results that are outside of their state and are getting discouraged. We think this defect might be the cause of their frustration.

I could not reproduce this issue on Chrome desktop browser, Safari Mobile Browser, or Firefox mobile browser.

# Expected Behavior
When I search for Triplers on the **/triplers/add** page using Chrome mobile browser, I see the results scrolled to the top of the results list.

# Screenshots

![Screenshot_20201004-105237](https://user-images.githubusercontent.com/8608070/95023267-fbf0ef00-0630-11eb-8e02-303861d0a76d.png)

![Screenshot_20201004-105316](https://user-images.githubusercontent.com/8608070/95023197-74a37b80-0630-11eb-8a4f-9c7af817a6f1.png)

**Comment by cooperka** [comment]
Unable to reproduce -- I certainly believe you that it's happening on your device, but I don't experience the issue on the same OS with same Chrome version, nor on an older OS with older Chrome version. I'm guessing this is probably a rare issue unless there are other circumstances that cause it.

[tested using both a physical device AND emulator, on a local dev version AND staging server]

Has anyone else encountered this by chance?
