### ISSUE TITLE
On /payments, if Stripe account connected, display last4 of account #, and if account is PayPal, display a different message

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#149]
As an ambassador, I want to see that my selected payment method is PayPal.

- On /payments, when an ambassador has selected PayPal as their payment method, under `Your payment account` header, show the following message `Your payments will be sent via PayPal to {email_address}.`
- Users who have selected PayPal will have `PYPL` returned to frontend in place of account number

**Comment by shrutimehta13** [comment]
<img width="816" alt="Screenshot 2020-10-10 at 6 02 24 PM" src="https://user-images.githubusercontent.com/34771314/95655188-29eb9d00-0b23-11eb-82e3-84160f570360.png">
