### ISSUE TITLE
Denied ambassador page

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#155]
As an ambassador, if I am denied I want to see a page informing me of my status.

- When an ambassador's account has been denied in admin dashboard, show them a new page when they login instead of redirecting them back to /ambassador/signup
- The new Denied Ambassador page should be a very basic page with the nav bar at the top (with the modifications below) and some text in the main page area (specified below)
- The nav should only show the logo the Sign Out button and the Help page icon. All other buttons should be hidden
- The page should have the following text appear on the page centered left/right and top/bottom:
`Your account is under review` << in header style (bold)
`Please contact support@blockpower.vote with any questions.` << in regular body style (unbolded)

**Comment by azrap** [comment]
@shauminn-colab I've coded this up! One thing that's different - rather than nav items hidden,  every page except the help page in the nav displays the "account is under review" message bc almost every page redirects to the ambassador/signup page.
