### ISSUE TITLE
Add required month/day field under Mobile Phone field on /triplers/confirm

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#162]
Add a required field for `{tripler_first_name}'s Birth Month and Day (MM/DD)` below `{tripler_first_name}'s Mobile Phone Number` field.

Ambassador must enter at least three characters to pass frontend validation but otherwise we accept any string entered

**Comment by azrap** [comment]
@shauminn-colab This has been completed and merged: https://github.com/colab-coop/hello-voter/pull/179
