### ISSUE TITLE
Filter defects

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#180]
1. Filtering by Sex doesn't currently work. The same results are shown regardless of which Sex is selected.  Look like frontend needs to pass F or M for gender
2. Small styling issue on phone number clear field button:
<img width="95" alt="Screen Shot 2020-10-22 at 2 49 28 PM" src="https://user-images.githubusercontent.com/71728947/96928989-a01ec680-1476-11eb-8bf0-9d33cbe3aa0c.png">

**Comment by shauminn-colab** [comment]
@cooperka getting closer!  Found a few issues, mostly minor:

-Filtering for Sex ONLY doesn't update the results - it shows the same Triplers whether I choose male or female
-Weird one: When filtering for Sex AND one other search or filter item, the first result at top of list is the same in both sets of results.  For example, I filtered "20-29" for age range and "Female" and clicked search (with no other search terms or filters set). First result is Mitchell Lakin on stage2. Then I changed to "Male" and clicked search again and results are updated, except that "Mitchell Lakin" is still the top result on the list. 
- First AND Last name search shows “nearby” in `Showing X search results for "firstname lastname, nearby"` even though first and last name equals 2 and therefore doesn't limit by zip code. So shouldn't say "nearby"

**Comment by cooperka** [comment]
Re: sex filter, are you sure the staging database has `gender` set properly to M/F/U? The sex filter always includes users with U so it's possible the nodes you're seeing are all U and show up in both searches (we could change this behavior if you want, it's sort of an arbitrary default). Assuming the data is not weird, then this is definitely a bug and I can try to diagnose it this weekend.

(or if you want to give me credentials for the stage2 Neo4j Browser I could check myself, up to you)

Re: name nearby, the word "nearby" is added to the search summary only depending on the distance slider. The slider defaults to "near me" (another arbitrary default we could change if you want). If you set the slider all the way to "doesn't matter" then "nearby" should go away. (The frontend does not know about the zip filter or points system, that's purely backend.)

**Comment by shauminn-colab** [comment]
I'll have to double check on gender data in stage2--very good point. Yea I am inclined to not show any U's in either the M or F filters.  

Ahh i gotcha about 'nearby' and toggle, makes sense. In that case, I'd just hide the "nearby" entirely in results header due to the cases where it's not accurate. And since in many cases it is showing Triplers nearby by default, seems ok to just hide in general.

**Comment by cooperka** [comment]
Will do! I will have time this evening.

**Comment by cooperka** [comment]
I submitted a couple PRs addressing the above; it has always worked locally so my hunch is that it's an issue with the stage2 data. Hard to debug beyond this so hope it helps!

**Comment by shauminn-colab** [comment]
Latest PRs merged, this looks great :) I think we are ready to deploy filters!
